root: true

env:
  es2021: true
  node: true

extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended

plugins:
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off

  prettier/prettier:
    - error
    - singleQuote: true
      semi: true
      trailingComma: all
      endOfLine: lf
